name: grain-analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - scipy
  - scikit-image
  - opencv
  - matplotlib
  - pillow
  - click
  - tqdm
  - libjpeg-turbo
  - libpng
  - jpeg
  - pandas
  - pytorch
  - pyright
  - torchvision
  - pip
  - pip:
      - imageio
      - medpy
      - transformers>=4.57.0
      - accelerate
      - safetensors
